name = "IdealGasThermoBenchmarks"
uuid = "d7e57dd0-6028-4f26-a39e-dc385f6fd2c4"
authors = ["Prashanth Prakash <prash@mit.edu> and contributors"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
IdealGasThermo = "d4fb33c0-2494-4384-b7a5-e5d0487b6649"
PkgBenchmark = "36db933b-70db-51c0-b978-0f229ee0e533"

[compat]
BenchmarkTools = "1"
PkgBenchmark = "1"
julia = "1.8 - 1"
